version: '3.8'
services:
  db:
    image: "postgres"
    container_name: post_db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: backend_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: nE5kMc7JCGNqwDQM
    volumes:
      - ./data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: dbViewer
    restart: always
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: lab@gmail.com
      PGADMIN_DEFAULT_PASSWORD: lab123@KA,2023

